<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSSumaWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSSumaWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSSumaWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://services.model.suma/">
    <import location="http://hp-probook:8080/sumaWeb/WSSuma?wsdl" namespace="http://services.model.suma/"/>
    <plnk:partnerLinkType name="WSSumaLinkType">
        <plnk:role name="WSSumaRole" portType="ns:WSSuma"/>
    </plnk:partnerLinkType>
</definitions>
